spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/authorization/**
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024